name: Deploy to ECR
on: 
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, tag, and push MySQL and WebApp images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        MYSQL_REPOSITORY: clo835_assign2-mysql  # ✅ Separate repository for MySQL
        WEBAPP_REPOSITORY: clo835_assign2-webapp  # ✅ Separate repository for WebApp
        IMAGE_TAG: v0.1
      run: |
        # Build MySQL Image
        docker build -t $ECR_REGISTRY/$MYSQL_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql .
        
        # Build WebApp Image
        docker build -t $ECR_REGISTRY/$WEBAPP_REPOSITORY:$IMAGE_TAG -f Dockerfile .
        
        # Push Images to Amazon ECR
        docker push $ECR_REGISTRY/$MYSQL_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$WEBAPP_REPOSITORY:$IMAGE_TAG
